export const POST_NEW_TASK_REQUEST = "POST_NEW_TASK_REQUEST"
export const POST_NEW_TASK_SUCCESS = "POST_NEW_TASK_SUCCESS"
export const POST_NEW_TASK_FAILURE = "POST_NEW_TASK_FAILURE"

export const GET_TODO_LIST_REQUEST = "GET_TODO_LIST_REQUEST"
export const GET_TODO_LIST_SUCCESS = "GET_TODO_LIST_SUCCESS"
export const GET_TODO_LIST_FAILURE = "GET_TODO_LIST_FAILURE"

export const GET_TASK_REQUEST = "GET_TASK_REQUEST"
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS"
export const GET_TASK_FAILURE = "GET_TASK_FAILURE"

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST"
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS"
export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE"

export const EDIT_TASK_REQUEST = "EDIT_TASK_REQUEST"
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS"
export const EDIT_TASK_FAILURE = "EDIT_TASK_FAILURE"

export const HANDLE_PAGE_CHANGE = "HANDLE_PAGE_CHANGE"